import type { BuildEventDossierInput, DossierStatement } from "../index";

export const statementFixture: DossierStatement = {
  id: "statement-1",
  text: "The official report confirms the meeting occurred.",
  statementType: "confirmed-fact",
  confidence: {
    score: 0.65,
    level: "high",
    reasons: ["evidence:1"],
    evidenceCount: 1,
    independentSourceCount: 1,
    primarySourceCount: 1,
    contradictionCount: 0,
    assessedAt: "2026-07-24T12:00:00.000Z",
    assessedBy: "human",
  },
  sourceDocumentIds: ["document-1"],
  claimIds: [],
  evidenceLinkIds: ["evidence-1"],
  dataPointIds: [],
  authoredBy: "human",
  createdAt: "2026-07-24T12:00:00.000Z",
};

export const dossierInputFixture = (): BuildEventDossierInput => ({
  event: {
    id: "event-1",
    title: "Regional summit",
    summary: "Leaders met for a regional summit",
    status: "confirmed",
    confidence: "high",
    startedAt: "2026-07-24T01:00:00.000Z",
    articleIds: [],
    entityIds: ["entity-1"],
    topicIds: [],
    locationEntityIds: [],
    createdAt: "2026-07-24T02:00:00.000Z",
    updatedAt: "2026-07-24T03:00:00.000Z",
  },
  sourceDocuments: [
    {
      id: "document-1",
      sourceId: "source-1",
      documentType: "GovernmentDocument",
      canonicalUrl: "https://government.example/report",
      title: "Official report",
      languageCode: "en",
      retrievedAt: "2026-07-24T04:00:00.000Z",
      authorNames: [],
      contentText: "Official report content",
      entityIds: ["entity-1"],
      topicIds: [],
      eventIds: ["event-1"],
    },
    {
      id: "document-2",
      sourceId: "source-2",
      documentType: "NewsArticle",
      canonicalUrl: "https://news.example/report",
      title: "Independent report",
      languageCode: "en",
      retrievedAt: "2026-07-24T05:00:00.000Z",
      authorNames: [],
      contentText: "Independent report content",
      entityIds: ["entity-1"],
      topicIds: [],
      eventIds: ["event-1"],
    },
  ],
  claims: [
    {
      id: "claim-1",
      sourceDocumentId: "document-1",
      statement: "The summit produced an agreement.",
      confidence: "high",
      attributedEntityIds: ["entity-1"],
      eventIds: ["event-1"],
      extractedAt: "2026-07-24T06:00:00.000Z",
    },
    {
      id: "claim-2",
      sourceDocumentId: "document-2",
      statement: "No final agreement was reached.",
      confidence: "medium",
      attributedEntityIds: ["entity-1"],
      eventIds: ["event-1"],
      extractedAt: "2026-07-24T06:10:00.000Z",
    },
  ],
  evidenceLinks: [
    {
      id: "evidence-1",
      sourceDocumentId: "document-1",
      targetType: "claim",
      targetId: "claim-1",
      relation: "supports",
      confidence: "high",
      createdAt: "2026-07-24T07:00:00.000Z",
    },
    {
      id: "evidence-2",
      sourceDocumentId: "document-2",
      targetType: "claim",
      targetId: "claim-1",
      relation: "contradicts",
      confidence: "medium",
      createdAt: "2026-07-24T07:10:00.000Z",
    },
  ],
  dataPoints: [
    {
      id: "data-1",
      sourceDocumentId: "document-1",
      name: "participants",
      value: 10,
      observedAt: "2026-07-24T01:00:00.000Z",
      confidence: "high",
      entityIds: [],
      eventIds: ["event-1"],
    },
    {
      id: "data-2",
      sourceDocumentId: "document-2",
      name: "participants",
      value: 12,
      observedAt: "2026-07-24T01:00:00.000Z",
      confidence: "medium",
      entityIds: [],
      eventIds: ["event-1"],
    },
  ],
  entities: [
    {
      id: "entity-1",
      type: "organization",
      canonicalName: "Regional Council",
      aliases: [],
    },
  ],
  statements: [statementFixture],
  timelineItems: [],
  openQuestions: [
    {
      id: "question-1",
      question: "Was the agreement legally binding?",
      importance: "critical",
      status: "open",
      requiredEvidenceTypes: ["LegalDocument"],
      relatedClaimIds: ["claim-1"],
      relatedEntityIds: ["entity-1"],
      createdAt: "2026-07-24T08:00:00.000Z",
    },
  ],
});
